version: '3'
services:
  app: &app
    build: .
    ports:
      - "5000:5000"
    command: flask run
    environment:
     - POSTGRES_USER=shortener
     - POSTGRES_PASSWORD=shortener
     - POSTGRES_DB=shortener
     - POSTGRES_HOST=url_shortener_postgres_1
     - POSTGRES_PORT=5432
     - APP_PORT=5000
    depends_on:
      - postgres
    networks:
      - ns

  deprecation: &deprecation
    build: .
    command: python url_shortener/deprecation_handler.py
    environment:
     - POSTGRES_USER=shortener
     - POSTGRES_PASSWORD=shortener
     - POSTGRES_DB=shortener
     - POSTGRES_HOST=url_shortener_postgres_1
     - POSTGRES_PORT=5432
     - APP_PORT=5100
    depends_on:
      - postgres
    networks:
      - ns

  postgres:
    image: postgres:latest
    environment:
     - POSTGRES_USER=shortener
     - POSTGRES_PASSWORD=shortener
     - POSTGRES_DB=shortener
     - POSTGRES_HOST=localhost
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ns

  check-format-imports:
    <<: *app
    command: isort --check-only -rc url_shortener tests
    depends_on: []
    volumes:
      - .:/usr/src/app

networks:
  ns:
    driver: bridge

